"use client";
import dynamic from "next/dynamic";
import { useEffect, useMemo, useRef, useState } from "react";
import type { SeriesMarker, Time } from "lightweight-charts";
import type { ReplayView, replayState } from "@smartvibe/agent/twinReplay.js";
import { emptyReplayLedger, replayEquity } from "@smartvibe/agent/twinReplayEngine.js";
import type { ChartActionTag, ChartAgentNote } from "./CoachChart";
import ReplayDiscussion from "./ReplayDiscussion";
import styles from "./replay.module.css";
const Chart = dynamic(() => import("./CoachChart"), { ssr: false });
type State = ReturnType<typeof replayState>;
const format = (n: number) => n.toLocaleString("zh-CN", { maximumFractionDigits: 8 });
const clock = (seconds: number) => new Date(seconds * 1000).toISOString().replace("T", " ").slice(0, 16);
async function api(动作: string, 参数: Record<string, unknown>) { const r = await fetch("/api/coach", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ 动作, 参数 }) }); const data = await r.json(); if (!r.ok) throw new Error(data.错误 || "演示暂不可用，请重试。"); return data; }
function validateScenario(values: { symbol: string; start: string; count: number; capital: number; marginPct: number; leverage: number; market: string }) {
  const errors: Record<string, string> = {};
  if (!/^[A-Z0-9]{2,20}$/.test(values.symbol)) errors.symbol = "请输入币种简称或交易对，例如 AKE 或 AKEUSDT。";
  const startMs = Date.parse(values.start);
  if (!values.start || !Number.isFinite(startMs)) errors.start = "请选择这段行情的大致开始时间。";
  else if (startMs >= Date.now()) errors.start = "开始时间必须早于现在。";
  if (!Number.isInteger(values.count) || values.count < 12 || values.count > 100) errors.count = "演示根数需要填写12—100之间的整数。";
  if (!Number.isFinite(values.capital) || values.capital < 100 || values.capital > 1_000_000) errors.capital = "虚拟本金需要填写100—1,000,000 USDT。";
  if (!Number.isFinite(values.marginPct) || values.marginPct < 1 || values.marginPct > 100) errors.marginPct = "首次投入比例需要填写1%—100%。";
  if (values.market === "U本位合约" && (!Number.isInteger(values.leverage) || values.leverage < 1 || values.leverage > 125)) errors.leverage = "杠杆需要填写1—125之间的整数。";
  return errors;
}

export default function TwinDemo({ twinId, busy: parentBusy, onBack, onPractice }: { twinId: string; busy: boolean; onBack: () => void; onPractice: () => void }) {
  const [state, setState] = useState<State>({ replay: null, sessions: [] });
  const [cursor, setCursor] = useState(0), [playing, setPlaying] = useState(false), [rate, setRate] = useState(2);
  const [busy, setBusy] = useState(false), [error, setError] = useState(""), [fieldErrors, setFieldErrors] = useState<Record<string, string>>({}), [form, setForm] = useState(false);
  const [preparing, setPreparing] = useState(false), [prepareElapsed, setPrepareElapsed] = useState(0);
  const [symbol, setSymbol] = useState("BTCUSDT"), [market, setMarket] = useState("U本位合约"), [marginMode, setMarginMode] = useState("全仓"), [direction, setDirection] = useState("做空");
  const [interval, setIntervalValue] = useState("1h"), [start, setStart] = useState(() => new Date(Date.now() - 7 * 86400000).toISOString().slice(0, 10) + "T00:00");
  const [count, setCount] = useState(30), [capital, setCapital] = useState(10000), [leverage, setLeverage] = useState(20), [marginPct, setMarginPct] = useState(20), [context, setContext] = useState("");
  const [entryPrice, setEntryPrice] = useState(""), [addPrice, setAddPrice] = useState(""), [entryQuantity, setEntryQuantity] = useState(""), [addQuantity, setAddQuantity] = useState("");
  const lock = useRef(false), createId = useRef<string | null>(null); const replay = state.replay, disabled = busy || parentBusy;
  const run = async (work: () => Promise<void>) => { if (lock.current) return; lock.current = true; setBusy(true); setError(""); try { await work(); } catch (e) { setPlaying(false); setError(e instanceof Error ? e.message : "请重试。"); } finally { lock.current = false; setBusy(false); } };
  const load = async (id?: string, autoPlay = false) => { const s: State = await api("分身演示状态", { 分身编号: twinId, 演示编号: id }); setState(s); setCursor(s.replay?.revealed ?? 0); setForm(!s.replay); setPlaying(autoPlay && !!s.replay && !s.replay.done); };
  useEffect(() => { void run(() => load()); }, [twinId]);
  useEffect(() => {
    if (!preparing) { setPrepareElapsed(0); return; }
    const startedAt = Date.now();
    const timer = window.setInterval(() => setPrepareElapsed(Math.floor((Date.now() - startedAt) / 1000)), 500);
    return () => window.clearInterval(timer);
  }, [preparing]);
  const advance = async () => { if (!replay) return; if (cursor < replay.revealed) { setCursor(cursor + 1); return; } if (replay.done) { setPlaying(false); return; } const next: ReplayView = await api("推进分身演示", { 分身编号: twinId, 演示编号: replay.id, 已展开: replay.revealed }); setState(old => ({ ...old, replay: next, sessions: old.sessions.map(s => s.id === next.id ? { ...s, revealed: next.revealed } : s) })); setCursor(next.revealed); if (next.done) setPlaying(false); };
  const frameMs = replay ? Math.max(250, 900000 / rate / replay.total) : 1000;
  useEffect(() => { if (!playing || disabled || !replay) return; if (replay.done && cursor === replay.total) { setPlaying(false); return; } const timer = window.setTimeout(() => void run(advance), frameMs); return () => window.clearTimeout(timer); }, [playing, disabled, cursor, replay, frameMs]);
  const candles = useMemo(() => replay ? [...replay.warmup, ...replay.candles.slice(0, cursor)] : [], [replay, cursor]);
  const isV2 = replay?.engineVersion === "replay-v2", frame = replay?.frames?.[cursor - 1], step = replay?.steps[cursor - 1];
  const ledger = frame?.ledger ?? step?.ledger ?? emptyReplayLedger(replay?.config.本金 ?? capital);
  const funds = frame ? { equity: frame.equity, cash: frame.ledger.cash, floating: frame.equity - frame.ledger.cash - (frame.ledger.position?.margin ?? 0), fees: frame.ledger.fees } : step?.equity ?? replayEquity(ledger as ReturnType<typeof emptyReplayLedger>, candles.at(-1)?.close ?? 0);
  const fills = ledger.fills ?? [];
  const resultSummary = useMemo(() => {
    const entry = fills.find(f => ["做多", "做空", "开多", "开空"].includes(f.action));
    if (!entry) return "这段演示中，分身没有建立仓位。";
    const adds = fills.filter(f => f.action === "加多" || f.action === "加空");
    const last = fills.at(-1)!;
    const directionText = entry.action.includes("空") ? "开空" : "开多";
    const addText = adds.length ? `，价格反向运行后又加仓${adds.length}次` : "";
    const ending = last.action === "强平" ? `，最终在 ${format(last.price)} 触发强平。` : `，最后以“${last.action}”结束这次演示。`;
    return `你的分身在 ${format(entry.price)} 选择${directionText}${addText}${ending}`;
  }, [fills]);
  const markers = useMemo<SeriesMarker<Time>[]>(() => fills.filter(f => !f.action.startsWith("开") && !f.action.startsWith("加") && !["做多", "做空"].includes(f.action)).map(f => ({ time: f.time as Time, position: f.action === "平空" ? "belowBar" : "aboveBar", color: f.action === "强平" ? "#ff9f43" : "#a9b7cc", shape: f.action === "平空" ? "arrowUp" : "arrowDown", text: `${f.action} ${format(f.price)}` })), [fills]);
  const actionTags = useMemo<ChartActionTag[]>(() => fills.filter(f => ["做多", "做空", "开多", "开空", "加多", "加空"].includes(f.action)).map(f => ({ time: f.time, side: f.action.includes("多") ? "long" : "short", title: f.action.replace("开多", "做多").replace("开空", "做空"), price: f.price })), [fills]);
  const agentNotes = useMemo<ChartAgentNote[]>(() => (replay?.frames ?? []).slice(0, cursor).filter(item => ["做多", "做空", "加多", "加空", "强平", "止损", "止盈"].includes(item.action)).flatMap((item, index) => {
    const fill = item.ledger.fills.at(-1); if (!fill) return [];
    return [{ time: fill.time, side: (replay?.config.方向 ?? "做多") === "做多" ? "long" as const : "short" as const, text: item.explanation, price: fill.price, lane: index % 3 }];
  }), [replay, cursor]);
  const position = frame?.ledger.position, entryLine = position ? { price: position.entry, title: "持仓均价" } : null;
  const remaining = replay ? Math.ceil(Math.max(0, replay.total - cursor) * frameMs / 1000) : 0;
  const prepareProgress = Math.min(92, Math.round(8 + prepareElapsed / 30 * 84));
  return <div className={styles.demo}>
    <header className={styles.heading}><div><p className="muted">第二阶段 · 分身演示</p><h1 className="h1">看看分身会如何决策</h1><p className="muted">选择一段与你经历有关的历史情境，然后像看电影一样观察分身交易。</p></div><div className={styles.headingActions}><button className="btn btn-primary" disabled={disabled || playing} onClick={() => { setForm(true); setPlaying(false); createId.current = null; window.setTimeout(() => document.getElementById("replay-scenario-setup")?.scrollIntoView({ behavior: "smooth", block: "start" }), 0); }}>重新选择交易情境</button><button className="btn" disabled={disabled || playing} onClick={onBack}>返回建立分身</button></div></header>
    {!!state.sessions.length && <div className={styles.historyBar}><label>已保存的演示 <select value={replay?.id ?? ""} disabled={disabled || playing} onChange={e => void run(() => load(e.target.value))}>{state.sessions.map(s => <option key={s.id} value={s.id}>{s.symbol} · {s.start.replace("T", " ").slice(0, 16)} · {s.revealed}/{s.total}根</option>)}</select></label><button className="btn" disabled={disabled || playing} onClick={() => { setForm(!form); createId.current = null; }}>{form ? "收起" : "选择新的交易情境"}</button></div>}
    {form && <section id="replay-scenario-setup" className={`card ${styles.setup}`}><h2 className="h2">选择你想观察的交易情境</h2><p className="muted">你提供经历，具体开仓位置和后续动作由分身决定。已有建档内容会作为判断依据。</p><div className={styles.fields} onChange={() => { createId.current = null; }}>
      <label>交易标的<input aria-invalid={!!fieldErrors.symbol} value={symbol} maxLength={20} placeholder="例如 AKE 或 AKEUSDT" onChange={e => { setSymbol(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, "")); setFieldErrors(old => ({ ...old, symbol: "" })); }} />{fieldErrors.symbol && <span className={styles.fieldError}>{fieldErrors.symbol}</span>}</label><label>市场<select value={market} onChange={e => { setMarket(e.target.value); if (e.target.value === "现货") setDirection("做多"); }}><option>U本位合约</option><option>现货</option></select></label>{market === "U本位合约" && <label>保证金模式<select value={marginMode} onChange={e => setMarginMode(e.target.value)}><option>全仓</option><option>逐仓</option></select></label>}<label>分身倾向<select value={direction} onChange={e => setDirection(e.target.value)}><option>做空</option><option>做多</option></select></label><label>K线周期<select value={interval} onChange={e => setIntervalValue(e.target.value)}><option value="5m">5分钟</option><option value="15m">15分钟</option><option value="1h">1小时</option><option value="4h">4小时</option></select></label><label>大致开始时间（本地时间）<input aria-invalid={!!fieldErrors.start} type="datetime-local" step={interval === "5m" ? 300 : 900} value={start} onChange={e => { setStart(e.target.value); setFieldErrors(old => ({ ...old, start: "" })); }} />{fieldErrors.start && <span className={styles.fieldError}>{fieldErrors.start}</span>}</label><label>演示根数<input aria-invalid={!!fieldErrors.count} type="number" min={12} max={100} value={count} onChange={e => { setCount(Number(e.target.value)); setFieldErrors(old => ({ ...old, count: "" })); }} />{fieldErrors.count && <span className={styles.fieldError}>{fieldErrors.count}</span>}</label><label>虚拟本金（USDT）<input aria-invalid={!!fieldErrors.capital} type="number" min={100} max={1000000} value={capital} onChange={e => { setCapital(Number(e.target.value)); setFieldErrors(old => ({ ...old, capital: "" })); }} />{fieldErrors.capital && <span className={styles.fieldError}>{fieldErrors.capital}</span>}</label><label>首次投入本金比例（%）<input aria-invalid={!!fieldErrors.marginPct} type="number" min={1} max={100} value={marginPct} onChange={e => { setMarginPct(Number(e.target.value)); setFieldErrors(old => ({ ...old, marginPct: "" })); }} />{fieldErrors.marginPct && <span className={styles.fieldError}>{fieldErrors.marginPct}</span>}</label>{market === "U本位合约" && <label>杠杆倍数<input aria-invalid={!!fieldErrors.leverage} type="number" min={1} max={125} value={leverage} onChange={e => { setLeverage(Number(e.target.value)); setFieldErrors(old => ({ ...old, leverage: "" })); }} />{fieldErrors.leverage && <span className={styles.fieldError}>{fieldErrors.leverage}</span>}</label>}</div>
      <details className={styles.exactSetup}><summary>按记忆中的具体价位复现（可选）</summary><p className="muted">填写后，分身会等待历史K线真正触及该价格。留空则由分身根据画像决定。</p><div className={styles.fields}><label>开仓参考价<input aria-invalid={!!fieldErrors.entryPrice} inputMode="decimal" value={entryPrice} placeholder="例如 0.016" onChange={e => { setEntryPrice(e.target.value); setFieldErrors(old => ({ ...old, entryPrice: "" })); }} />{fieldErrors.entryPrice && <span className={styles.fieldError}>{fieldErrors.entryPrice}</span>}</label><label>开仓数量<input aria-invalid={!!fieldErrors.entryQuantity} inputMode="decimal" value={entryQuantity} placeholder="例如 20000" onChange={e => { setEntryQuantity(e.target.value); setFieldErrors(old => ({ ...old, entryQuantity: "" })); }} />{fieldErrors.entryQuantity && <span className={styles.fieldError}>{fieldErrors.entryQuantity}</span>}</label><label>加仓参考价<input aria-invalid={!!fieldErrors.addPrice} inputMode="decimal" value={addPrice} placeholder="例如 0.02" onChange={e => { setAddPrice(e.target.value); setFieldErrors(old => ({ ...old, addPrice: "" })); }} />{fieldErrors.addPrice && <span className={styles.fieldError}>{fieldErrors.addPrice}</span>}</label><label>加仓数量<input aria-invalid={!!fieldErrors.addQuantity} inputMode="decimal" value={addQuantity} placeholder="例如 20000" onChange={e => { setAddQuantity(e.target.value); setFieldErrors(old => ({ ...old, addQuantity: "" })); }} />{fieldErrors.addQuantity && <span className={styles.fieldError}>{fieldErrors.addQuantity}</span>}</label></div></details>
      <label className={styles.context}>补充你对这段交易的印象（可选）<textarea rows={3} maxLength={1000} value={context} placeholder="例如：我习惯在1小时 RSI 超过85时做空，价格继续上涨时会扛单或加仓……" onChange={e => setContext(e.target.value)} /></label><p className="muted">分身会在播放前形成一次策略，播放时不会看到后续K线。{market === "U本位合约" ? marginMode === "全仓" ? "全仓模式下，未投入资金也会共同承担持仓亏损。" : "逐仓模式下，只有分配给当前仓位的保证金承担亏损。" : "现货不使用合约保证金。"}</p><div className={styles.prepareRow}><button className="btn btn-primary" disabled={disabled} onClick={() => { const invalid = validateScenario({ symbol, start, count, capital, marginPct, leverage, market }); const optional = { entryPrice: entryPrice ? Number(entryPrice) : null, addPrice: addPrice ? Number(addPrice) : null, entryQuantity: entryQuantity ? Number(entryQuantity) : null, addQuantity: addQuantity ? Number(addQuantity) : null }; for (const [key, value] of Object.entries(optional)) if (value !== null && (!Number.isFinite(value) || value <= 0)) invalid[key] = "请输入大于0的数字，或将这一项留空。"; setFieldErrors(invalid); if (Object.keys(invalid).length) { setError("有些设置需要修改，具体位置已经用红字标出。"); return; } setPreparing(true); void run(async () => { try { createId.current ??= crypto.randomUUID(); const seconds = interval === "5m" ? 300 : interval === "15m" ? 900 : interval === "1h" ? 3600 : 14400; const aligned = new Date(Math.floor(Date.parse(start) / (seconds * 1000)) * seconds * 1000).toISOString(); const r: ReplayView = await api("创建分身演示", { 分身编号: twinId, 请求编号: createId.current, 交易对: symbol, 市场: market, 保证金模式: marginMode, 方向: direction, 杠杆: market === "现货" ? 1 : leverage, 投入比例: marginPct, 情境描述: context, 开仓参考价: optional.entryPrice, 加仓参考价: optional.addPrice, 开仓数量: optional.entryQuantity, 加仓数量: optional.addQuantity, 周期: interval, 开始时间: aligned, 根数: count, 本金: capital }); await load(r.id, true); createId.current = null; } finally { setPreparing(false); } }); }}>{preparing ? "Agent正在准备策略…" : "让分身准备这段演示"}</button>{preparing && <div className={styles.prepareProgress} role="status" aria-live="polite"><div><span>正在读取行情并整理分身策略</span><strong>{prepareProgress}%</strong></div><progress max={100} value={prepareProgress} /><small>{prepareElapsed < 30 ? `预计还需约 ${Math.max(1, 30 - prepareElapsed)} 秒` : "正在完成最后整理…"}</small></div>}</div>
    </section>}
    {error && <p role="alert" className="error-box">{error} 已完成的过程会保留。</p>}
    {replay && <section className={`card ${styles.player}`}><div className={styles.controls}><strong>{replay.config.交易对} · {replay.config.市场 ?? "现货"} · {replay.config.周期} · {cursor}/{replay.total}根</strong><button className="btn btn-primary" disabled={parentBusy || (!playing && busy) || (replay.done && cursor === replay.total)} onClick={() => setPlaying(!playing)}>{replay.done && cursor === replay.total ? "播放完成" : playing ? "暂停" : cursor ? "继续播放" : "开始播放"}</button><button className="btn" disabled={disabled || playing || (replay.done && cursor === replay.total)} onClick={() => void run(advance)}>下一根</button><button className="btn" disabled={disabled || playing || !cursor} onClick={() => setCursor(0)}>从头回看</button><label aria-label="播放速度"><select className={styles.rateSelect} aria-label="播放速度" value={rate} onChange={e => setRate(Number(e.target.value))}><option value={1}>1× · 全程约15分钟</option><option value={2}>2× · 全程约7.5分钟</option><option value={5}>5× · 全程约3分钟</option></select></label></div>
      <p className="muted">{rate}×播放 · 预计还需 {Math.floor(remaining / 60)}分{remaining % 60}秒。播放中可随时调整速度。</p><input className={styles.seek} type="range" min={0} max={replay.revealed} value={cursor} disabled={disabled || playing} onChange={e => setCursor(Number(e.target.value))} /><div className={styles.funds}>{Object.entries({ "虚拟权益": funds.equity, "可用资金": funds.cash, "浮动盈亏": funds.floating, "净盈亏": funds.equity - replay.config.本金, "累计手续费": funds.fees }).map(([name, value]) => <div key={name}><span>{name}</span><strong>{format(value)}</strong></div>)}</div><div className={styles.chartStage}><Chart candles={candles} markers={markers} actionTags={actionTags} agentNotes={agentNotes} entryLine={entryLine} compact /></div><p className="muted">{replay.source} · 图表时间UTC · {candles.length ? `当前至 ${clock(candles.at(-1)!.time)}` : "尚未播放"} · 红色向下标签做空，绿色向上标签做多</p>
      <div className={styles.liveDecision} aria-live="polite"><span>{frame?.action ?? (step?.decision.动作 === "观望" && (ledger as { position?: unknown }).position ? "继续持有" : step?.decision.动作) ?? "分身策略已准备"}</span><p>{frame?.explanation ?? step?.decision.理由 ?? "点击开始播放，观察分身在这段历史情境中的交易动作。"}</p>{position && <small>当前持{position.side}仓 · 均价 {format(position.entry)} · {replay.config.保证金模式 ?? "逐仓"}模拟强平线 {format(position.liquidation)}</small>}</div><details className={`muted ${styles.methodology}`}><summary>查看本次策略与模拟口径</summary>{isV2 && <><p>Agent在播放前根据画像和当时已经收盘的K线形成策略，播放过程中由本地引擎逐根执行，不读取后续K线。</p><p>{replay.policy?.habitBasis}</p></>}<p>{isV2 ? `U本位合约使用${replay.config.保证金模式 ?? "逐仓"}教学模拟口径与简化维持保证金率计算强平线；未计历史资金费率和交易所分档变化。` : "这是旧版逐根模型演示，仍按创建时规则播放。"}</p></details>{busy && <p role="status" className="muted">正在推进下一段…</p>}</section>}
    {replay?.done && cursor === replay.total && <div className={styles.afterGrid}><section className={`card ${styles.result}`}><h2>本次演示说明</h2><p>虚拟本金 {format(replay.config.本金)} USDT → 结束权益 {format(funds.equity)} USDT</p><p>净盈亏 {format(funds.equity - replay.config.本金)} USDT</p>{replay.policy && <><h3>分身这次怎么做的</h3><p>{resultSummary}</p><p className="muted">分身依据：{replay.policy.habitBasis}</p></>}<p className="muted">这次演示用于观察交易行为，不用于预测之后的收益。</p></section><ReplayDiscussion className={styles.replayChat} key={replay.id} twinId={twinId} replayId={replay.id} /></div>}
    {!replay && busy && <p role="status" className="muted">正在读取历史行情并让 Agent 准备策略…</p>}<div className={styles.next}><button className={`btn btn-primary ${styles.practiceButton}`} disabled={disabled || playing} onClick={onPractice}><strong>进入自主练习</strong><span>交易陪练始终在你身边</span></button></div>
  </div>;
}
